metadata_unencrypted:
    environment: production
    description: Encrypted production secrets for Sheshi. Values are decrypted only on the VM.
secrets:
    db_password: ENC[AES256_GCM,data:PHaWana5COhNwcBSO9m+LBDCtuJt1Boe0dZkZNSkAmu9FlWl9B9V3Nav92kjzm5p,iv:IUP4qhzXrTVkvJE1b73ehKK3JiFSS2s7IWkQy915Za4=,tag:R7+eakIfs9KzJSLFweaTWA==,type:str]
    db_connection_string: ENC[AES256_GCM,data:cekLamMIQpnxtnc8jiEj3EUfnvCr0SY8ifrhYFBeiGcjpj2uTexFPl7UzXD7gq5JQFr37wrpjYseUAh0KkA7V2nZQurQLLos6tY45JNY7YetyzTTecbJ+5NzDe/pz3/MzX+DqB+X0lBjhwA=,iv:roh1pMq/NKFwK9EXAWDiWg87qNGLcksQ4mGSdM4YVP0=,tag:oOD+q71lssRApxwDYpmLgQ==,type:str]
    jwt_signing_key: ENC[AES256_GCM,data:rbqnjjuPvQGN0Bsw0IEP0Quh5TuWYmvWxHTmgdBfh7WmzcPQOQVkUXwtVxUcOhHS5HcOab1yfd8erqz1qm2X9vMX2Xx/Xc5Koom3+qcqUuLxlogfsADEjw==,iv:G33K7tDu3gTYfskzMMzrR/JpiKheY25KswpYxFz+YyM=,tag:0pu/1jPY19Y7p2uQkVoomg==,type:str]
    smtp_password: ENC[AES256_GCM,data:wyBitujHfWf5gwSGVpeOruIgsaGOtXoIXLTp8hcq2HJkVNDQddMW4CnZR/mpNefR,iv:At9twOLxnf4G7F5AMlwCEOqx2TtfqnLSGcbSGmEznN0=,tag:+vajp7GErMBCH5pxxgIOfQ==,type:str]
    object_storage_access_key: ENC[AES256_GCM,data:kKEt3DtCVgxBKJ7nCjFVuUyWdOuVAJ1opj6QNaeXvYU=,iv:EWyOLskyNfTqznuICwf7ZBugjix/FbKHuNo9csLrZm0=,tag:f5IssO2gdncpMAlYuZtLWA==,type:str]
    object_storage_secret_key: ENC[AES256_GCM,data:giiV5+1XhXm9hppv809J04Ed/V3z21j2STpNZzICjMXA5+gdQIbXt4h+VcjJvcvtgr24DVh1kpqPnBV+al/5qA==,iv:5Hq8meTj+NJ7eq5VZPbmnGmKjpbt5JiJTQ3IOBoVQTI=,tag:tqOOwkoS9vypjPxvteURXw==,type:str]
    backup_storage_access_key: ENC[AES256_GCM,data:sPy5KIXmmdPYIKuv0vxdU4DbZeu7JHjLuB2yr+HrnpI=,iv:giLqEbwvKHExmnBQlhhHY66tTCEScrK1TvftMgTmpP0=,tag:ScC4fbRcIG4+0pyQTsXG8A==,type:str]
    backup_storage_secret_key: ENC[AES256_GCM,data:NH6LQo4W9QBhCxxuAt+JxCrKRugrclzFEEkXyKxCECFVxyrgyzqoxKG8o/+06ow+PtRavxKdyVOEY/kjL9GNDg==,iv:l2a0hW2ekvxwSY7VWJ+jX3v7EVgMi2jczu+PfEmQeSA=,tag:C4CXENsZSEva9dWOwUEmkA==,type:str]
    backup_encryption_key: ENC[AES256_GCM,data:wVJACk2yiCD1BrWVhQEISvr5ca+6+Pc/xYEjYxCZr0OhdZJ6JwuZJk+MJdyc/g5y9Pe6iGMNsYgCysOf4XTB+Q==,iv:io8DwtzVcUZKw6MGxgB9C+Mmxcd4BYMALeqJSyNJl7Q=,tag:MxTU6gExxjT3SM32PA0S7A==,type:str]
sops:
    age:
        - recipient: age1s7x558ammztlrxzvth07rayz8wp4wclqh59nhyrvzelz4tranq7sux2qmt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1a1ZyQlFMdTBHY1B3NCs5
            K2ozUlQ4ZGQ5OEdmWjFnNWdpM1Q4NW55ZlRNCjVWK2tCakxxQkFXR2lmcWxyV2JF
            UytadThPelhTSUo2enRjc1dmWVI4VzAKLS0tIEVOeDV3WG83V0k1MmRyaHNPTEFF
            K1lvaGh4bW9KaS81YnBsOE5LNWh5WDQKjkxdWDV+cNHmnns2zZbURQXVpZOzUVjG
            6le/oRsl9NSi+6cpWU7eNBgGlAENPR2b6tiEtQjiq2Hgnskrj3/R1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-14T17:47:05Z"
    mac: ENC[AES256_GCM,data:ub69cFJ1YCqPj2SRJEQi2k3amoBmKRX0jWgk8+w1qob9NC3KOxVtVVkdjA214LhWqhWJlujVqPqRYcSKtshJnoesRv+H93ZWkU9zzY6Cgvye3dgxCCk+qXG/JMyHrtJu/8tSsEQAOFu9PppenbucE1i7RltuL5AAYa5ji4bbW3M=,iv:Dw8Iovy4GrnYTbTETsjWVV4f9vIFplZbB6Dlz6oVrZA=,tag:jsxb8kxMvae4mfRFaDj9vw==,type:str]
    encrypted_regex: ^(db_password|db_connection_string|jwt_signing_key|smtp_password|object_storage_access_key|object_storage_secret_key|backup_storage_access_key|backup_storage_secret_key|backup_encryption_key)$
    version: 3.12.2
