/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfiliRouteImport } from './routes/profili'
import { Route as ModerimRouteImport } from './routes/moderim'
import { Route as FokusRouteImport } from './routes/fokus'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemaMessageIdRouteImport } from './routes/tema.$messageId'
import { Route as DhomaSlugRouteImport } from './routes/dhoma.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfiliRoute = ProfiliRouteImport.update({
  id: '/profili',
  path: '/profili',
  getParentRoute: () => rootRouteImport,
} as any)
const ModerimRoute = ModerimRouteImport.update({
  id: '/moderim',
  path: '/moderim',
  getParentRoute: () => rootRouteImport,
} as any)
const FokusRoute = FokusRouteImport.update({
  id: '/fokus',
  path: '/fokus',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemaMessageIdRoute = TemaMessageIdRouteImport.update({
  id: '/tema/$messageId',
  path: '/tema/$messageId',
  getParentRoute: () => rootRouteImport,
} as any)
const DhomaSlugRoute = DhomaSlugRouteImport.update({
  id: '/dhoma/$slug',
  path: '/dhoma/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/fokus': typeof FokusRoute
  '/moderim': typeof ModerimRoute
  '/profili': typeof ProfiliRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dhoma/$slug': typeof DhomaSlugRoute
  '/tema/$messageId': typeof TemaMessageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/fokus': typeof FokusRoute
  '/moderim': typeof ModerimRoute
  '/profili': typeof ProfiliRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dhoma/$slug': typeof DhomaSlugRoute
  '/tema/$messageId': typeof TemaMessageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/fokus': typeof FokusRoute
  '/moderim': typeof ModerimRoute
  '/profili': typeof ProfiliRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dhoma/$slug': typeof DhomaSlugRoute
  '/tema/$messageId': typeof TemaMessageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/fokus'
    | '/moderim'
    | '/profili'
    | '/reset-password'
    | '/sitemap.xml'
    | '/auth/callback'
    | '/dhoma/$slug'
    | '/tema/$messageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/fokus'
    | '/moderim'
    | '/profili'
    | '/reset-password'
    | '/sitemap.xml'
    | '/auth/callback'
    | '/dhoma/$slug'
    | '/tema/$messageId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/fokus'
    | '/moderim'
    | '/profili'
    | '/reset-password'
    | '/sitemap.xml'
    | '/auth/callback'
    | '/dhoma/$slug'
    | '/tema/$messageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  FokusRoute: typeof FokusRoute
  ModerimRoute: typeof ModerimRoute
  ProfiliRoute: typeof ProfiliRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DhomaSlugRoute: typeof DhomaSlugRoute
  TemaMessageIdRoute: typeof TemaMessageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profili': {
      id: '/profili'
      path: '/profili'
      fullPath: '/profili'
      preLoaderRoute: typeof ProfiliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderim': {
      id: '/moderim'
      path: '/moderim'
      fullPath: '/moderim'
      preLoaderRoute: typeof ModerimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fokus': {
      id: '/fokus'
      path: '/fokus'
      fullPath: '/fokus'
      preLoaderRoute: typeof FokusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tema/$messageId': {
      id: '/tema/$messageId'
      path: '/tema/$messageId'
      fullPath: '/tema/$messageId'
      preLoaderRoute: typeof TemaMessageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dhoma/$slug': {
      id: '/dhoma/$slug'
      path: '/dhoma/$slug'
      fullPath: '/dhoma/$slug'
      preLoaderRoute: typeof DhomaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  FokusRoute: FokusRoute,
  ModerimRoute: ModerimRoute,
  ProfiliRoute: ProfiliRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DhomaSlugRoute: DhomaSlugRoute,
  TemaMessageIdRoute: TemaMessageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
